/**
 * Templates Module
 * Pre-made templates for common use cases
 */

export const templates = {
  'homepage-hero': {
    name: 'Homepage Hero',
    description: 'Bold hero style for homepage',
    state: {
      preset: 'hero',
      title: 'Logi-Ink',
      subtitle: 'Digital Innovation & Creative Solutions',
      slogan: 'Transforming Ideas Into Reality',
      titleColor: 'cyan',
      subtitleColor: 'text-secondary',
      sloganColor: 'magenta',
      titleSize: 80,
      subtitleSize: 32,
      sloganSize: 24,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: true,
      logoPosition: 'top-left',
      logoSize: 140,
    },
  },
  'service-page': {
    name: 'Service Page',
    description: 'Professional service page style',
    state: {
      preset: 'service',
      title: 'Our Services',
      subtitle: 'Comprehensive Digital Solutions',
      slogan: '',
      titleColor: 'cyan',
      subtitleColor: 'text-secondary',
      sloganColor: 'magenta',
      titleSize: 70,
      subtitleSize: 28,
      sloganSize: 20,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: false,
      logoPosition: 'top-right',
      logoSize: 120,
    },
  },
  'minimal-clean': {
    name: 'Minimal Clean',
    description: 'Clean minimal design',
    state: {
      preset: 'minimal',
      title: 'Logi-Ink',
      subtitle: 'Simple. Effective. Powerful.',
      slogan: '',
      titleColor: 'white',
      subtitleColor: 'text-secondary',
      sloganColor: 'cyan',
      titleSize: 68,
      subtitleSize: 26,
      sloganSize: 20,
      titleGlow: false,
      subtitleGlow: false,
      sloganGlow: false,
      logoPosition: 'center',
      logoSize: 150,
    },
  },
  'cyberpunk-tech': {
    name: 'Cyberpunk Tech',
    description: 'High-tech cyberpunk aesthetic',
    state: {
      preset: 'cyberpunk',
      title: 'TECH INNOVATION',
      subtitle: 'Next Generation Solutions',
      slogan: 'Pushing Boundaries',
      titleColor: 'cyan',
      subtitleColor: 'magenta',
      sloganColor: 'green',
      titleSize: 76,
      subtitleSize: 30,
      sloganSize: 22,
      titleGlow: true,
      subtitleGlow: true,
      sloganGlow: true,
      logoPosition: 'top-left',
      logoSize: 130,
    },
  },
  'announcement': {
    name: 'Announcement',
    description: 'Bold announcement style',
    state: {
      preset: 'gradient',
      title: 'NEW RELEASE',
      subtitle: 'Check Out Our Latest Features',
      slogan: 'Available Now',
      titleColor: 'magenta',
      subtitleColor: 'cyan',
      sloganColor: 'yellow',
      titleSize: 74,
      subtitleSize: 28,
      sloganSize: 24,
      titleGlow: true,
      subtitleGlow: true,
      sloganGlow: true,
      logoPosition: 'bottom-right',
      logoSize: 110,
    },
  },
  'portfolio-showcase': {
    name: 'Portfolio Showcase',
    description: 'Showcase portfolio work',
    state: {
      preset: 'particles',
      title: 'Our Work',
      subtitle: 'Creative Excellence',
      slogan: 'See What We Can Do',
      titleColor: 'cyan',
      subtitleColor: 'text-secondary',
      sloganColor: 'magenta',
      titleSize: 72,
      subtitleSize: 28,
      sloganSize: 20,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: false,
      logoPosition: 'top-left',
      logoSize: 120,
    },
  },
  'testimonial': {
    name: 'Testimonial',
    description: 'Client testimonial style',
    state: {
      preset: 'minimal',
      title: 'Client Success',
      subtitle: 'What Our Clients Say',
      slogan: 'Trusted by Industry Leaders',
      titleColor: 'gold',
      subtitleColor: 'text-secondary',
      sloganColor: 'cyan',
      titleSize: 66,
      subtitleSize: 26,
      sloganSize: 20,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: false,
      logoPosition: 'center',
      logoSize: 140,
    },
  },
  'product-launch': {
    name: 'Product Launch',
    description: 'Exciting product launch style',
    state: {
      preset: 'neon',
      title: 'PRODUCT LAUNCH',
      subtitle: 'Revolutionary New Features',
      slogan: 'Coming Soon',
      titleColor: 'magenta',
      subtitleColor: 'cyan',
      sloganColor: 'green',
      titleSize: 78,
      subtitleSize: 30,
      sloganSize: 24,
      titleGlow: true,
      subtitleGlow: true,
      sloganGlow: true,
      logoPosition: 'top-center',
      logoSize: 125,
    },
  },
  'about-us': {
    name: 'About Us',
    description: 'Professional about page style',
    state: {
      preset: 'service',
      title: 'About Logi-Ink',
      subtitle: 'Our Story & Mission',
      slogan: 'Innovation Through Design',
      titleColor: 'cyan',
      subtitleColor: 'text-secondary',
      sloganColor: 'magenta',
      titleSize: 70,
      subtitleSize: 28,
      sloganSize: 22,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: true,
      logoPosition: 'top-left',
      logoSize: 120,
    },
  },
  'contact-page': {
    name: 'Contact Page',
    description: 'Contact page style',
    state: {
      preset: 'minimal',
      title: 'Get In Touch',
      subtitle: 'Let\'s Start a Conversation',
      slogan: 'We\'d Love to Hear From You',
      titleColor: 'cyan',
      subtitleColor: 'text-secondary',
      sloganColor: 'magenta',
      titleSize: 68,
      subtitleSize: 26,
      sloganSize: 20,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: false,
      logoPosition: 'center',
      logoSize: 130,
    },
  },
  'blog-post': {
    name: 'Blog Post',
    description: 'Blog post header style',
    state: {
      preset: 'gradient',
      title: 'Blog Title',
      subtitle: 'Insights & Updates',
      slogan: '',
      titleColor: 'cyan',
      subtitleColor: 'text-secondary',
      sloganColor: 'magenta',
      titleSize: 70,
      subtitleSize: 28,
      sloganSize: 20,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: false,
      logoPosition: 'top-left',
      logoSize: 110,
    },
  },
  'case-study': {
    name: 'Case Study',
    description: 'Case study showcase style',
    state: {
      preset: 'cyberpunk',
      title: 'CASE STUDY',
      subtitle: 'Client Success Story',
      slogan: 'Real Results. Real Impact.',
      titleColor: 'magenta',
      subtitleColor: 'cyan',
      sloganColor: 'green',
      titleSize: 74,
      subtitleSize: 30,
      sloganSize: 22,
      titleGlow: true,
      subtitleGlow: true,
      sloganGlow: true,
      logoPosition: 'top-right',
      logoSize: 120,
    },
  },
  'pricing-page': {
    name: 'Pricing Page',
    description: 'Pricing page header',
    state: {
      preset: 'service',
      title: 'Pricing Plans',
      subtitle: 'Choose Your Package',
      slogan: 'Transparent. Affordable. Powerful.',
      titleColor: 'cyan',
      subtitleColor: 'text-secondary',
      sloganColor: 'gold',
      titleSize: 72,
      subtitleSize: 28,
      sloganSize: 20,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: true,
      logoPosition: 'top-left',
      logoSize: 115,
    },
  },
  'event-announcement': {
    name: 'Event Announcement',
    description: 'Event or webinar announcement',
    state: {
      preset: 'neon',
      title: 'UPCOMING EVENT',
      subtitle: 'Join Us for an Exclusive Webinar',
      slogan: 'Register Now - Limited Seats',
      titleColor: 'magenta',
      subtitleColor: 'cyan',
      sloganColor: 'yellow',
      titleSize: 76,
      subtitleSize: 30,
      sloganSize: 24,
      titleGlow: true,
      subtitleGlow: true,
      sloganGlow: true,
      logoPosition: 'top-center',
      logoSize: 125,
    },
  },
  'feature-highlight': {
    name: 'Feature Highlight',
    description: 'Highlight a new feature',
    state: {
      preset: 'particles',
      title: 'NEW FEATURE',
      subtitle: 'Enhanced Capabilities',
      slogan: 'Experience the Difference',
      titleColor: 'green',
      subtitleColor: 'cyan',
      sloganColor: 'magenta',
      titleSize: 72,
      subtitleSize: 28,
      sloganSize: 22,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: true,
      logoPosition: 'bottom-right',
      logoSize: 110,
    },
  },
  'thank-you': {
    name: 'Thank You',
    description: 'Thank you or confirmation page',
    state: {
      preset: 'minimal',
      title: 'Thank You!',
      subtitle: 'We Appreciate Your Interest',
      slogan: 'We\'ll Be In Touch Soon',
      titleColor: 'green',
      subtitleColor: 'text-secondary',
      sloganColor: 'cyan',
      titleSize: 70,
      subtitleSize: 28,
      sloganSize: 20,
      titleGlow: true,
      subtitleGlow: false,
      sloganGlow: false,
      logoPosition: 'center',
      logoSize: 140,
    },
  },
  'coming-soon': {
    name: 'Coming Soon',
    description: 'Coming soon page style',
    state: {
      preset: 'matrix',
      title: 'COMING SOON',
      subtitle: 'Something Amazing is on the Way',
      slogan: 'Stay Tuned',
      titleColor: 'cyan',
      subtitleColor: 'magenta',
      sloganColor: 'green',
      titleSize: 78,
      subtitleSize: 30,
      sloganSize: 24,
      titleGlow: true,
      subtitleGlow: true,
      sloganGlow: true,
      logoPosition: 'center',
      logoSize: 150,
    },
  },
};

/**
 * Get template by key
 * @param {string} key - Template key
 * @returns {Object|null} Template or null
 */
export function getTemplate(key) {
  return templates[key] || null;
}

/**
 * Get all templates
 * @returns {Object} All templates
 */
export function getAllTemplates() {
  return templates;
}

/**
 * Apply template to state
 * @param {string} key - Template key
 * @returns {Object|null} Template state or null
 */
export function applyTemplate(key) {
  const template = getTemplate(key);
  return template ? template.state : null;
}

